'''
This detects halucination generated by SQL by verifying that the SQL actually 
answers the question that was asked.
'''
from typing import List
import sqlparse
import decimal
import re 
import json
import logging
from typing import Dict, Any
from openai import OpenAI
from dotenv import load_dotenv
from datetime import datetime
import pandas as pd
# pyrefly: ignore [missing-import]
from logger import get_logger
logger = get_logger(__name__)
# pyrefly: ignore [missing-import]
from query_executor import QueryExecutor

load_dotenv()

# Threshold below which we flag a query as potentially halucinated 
# 0.5 means 50%, less than that then the question doesnt match with the desired answer
ALIGNMENT_THRESHOLD=0.5 

class BackTranslationVerifier:
    def __init__(self):
        """Initializes OpenAI for backTranslation API calls"""
        self.client=OpenAI()
    
    def back_translate(self,sql:str)->str:
        """"This asks LLM what question does this SQL answer"""

        prompt=f'''You are a SQL Expert. Given the following SQL query, describe in one simple sentence,
        what question this query answers. Be specific about what data is being retrieved and how it is aggregated.
        Return only the question and nothing else
        
        SQL Query:{sql}
        
        Question this SQL answers:'''

        response=self.client.chat.completions.create(
            model='gpt-4o-mini',
            messages=[
                {
                    'role':'system',
                    'content':'''You are a SQL expert. You read SQL queries and describe in plain english',
                                'what question they answer. Always respond in one sentence.'''
                },
                {
                    'role':'user',
                    'content':prompt
                }
            ],
            temperature=0,
            max_tokens=100
        )

        return response.choices[0].message.content.strip() # type: ignore

    def keyword_overlap_score(self,question1:str,question2:str)->float:
        """Calculates similarity between two questions using word overlap
        question1-> the orignal user question
        question2-> the back translated quesiton from the LLM
        """

        stop_words = {
            "what", "which", "who", "how", "many", "much", "show",
            "me", "the", "a", "an", "is", "are", "was", "were",
            "have", "has", "had", "do", "does", "did", "will",
            "would", "could", "should", "can", "may", "might",
            "of", "in", "on", "at", "to", "for", "with", "by",
            "from", "and", "or", "but", "all", "most", "list",
            "get", "give", "find", "tell", "this", "that", "these"
        }

        # extract keywords from both the questions
        words1={
            w for w in re.findall(r'[a-zA-Z]+',question1.lower())
            if w not in stop_words
        }

        words2={
            w for w in re.findall(r'[a-zA-Z]+',question2.lower())
            if w not in stop_words
        }

        if not words1 or not words2:
            # If either set is empty, return 0 to avoid division by zero
            return 0.0

        # Using jaccards similarity score to find the similarity between the two questions
        intersection=words1&words2
        union=words1 | words2

        return len(intersection) / len(union)

    def llm_similarity_score(self,orignal_question:str,back_translated_question:str)->float:
        """Asking the LLM to score how semantically similar two quesiton are."""
        prompt=f'''Compare these two questions and rate how similar they are in meaning on a scale of 0.0 to 1.0
                Question 1: {orignal_question}
                Question 2: {back_translated_question}
                
                Scoring guide:
                1.0 = identical meaning
                0.8 = very similar, minor wording differences  
                0.6 = related but one is more specific than the other
                0.4 = somewhat related but answering different aspects
                0.2 = loosely related
                0.0 = completely different questions

                Respond with only a json object like this:
                {{'similarity_score': 0.0,'resoning':"one sentence explanation"}}
                '''

        response=self.client.chat.completions.create(
            model='gpt-4o-mini',
            messages=[
                {
                    'role':'system',
                    'content':('You are an expert at comparing quesiton similarity. Always respond with valid JSON only.')
                },
                {
                    'role':'user',
                    'content':prompt
                }
            ],
            temperature=0,
            max_tokens=100
        )

        # Parse the JSON response
        try:
            raw=response.choices[0].message.content.strip() #type:ignore
            # Remove markdown code fences if any
            if raw.startswith('```'):
                raw=raw[raw.find('\n'):].replace('```','').strip()
            parsed=json.loads(raw)
            return float(parsed.get('similarity_score',0.0))
        except(json.JSONDecodeError,ValueError):
            # If parsing fails retunr the neutral middle score
            return 0.5
    
    def verify(self,original_question:str,sql:str)->Dict[str,Any]:

        logger.info(f"Running back-translation for: {original_question[:50]}...")

        # Back Translate SQL to question
        back_translated_question=self.back_translate(sql)

        #Keyword Overlap
        keyword_score=self.keyword_overlap_score(original_question,back_translated_question)

        # LLM Similarity score
        semantic_score=self.llm_similarity_score(original_question,back_translated_question)

        # Weighted scores of both because LLM understand the questions meaning better
        alignment_score = (0.3 * keyword_score) + (0.7 * semantic_score)

        # Check if halucination
        is_hallucination= alignment_score < ALIGNMENT_THRESHOLD
        if is_hallucination:
            logger.warning(f'Potential hallucination - alignment score: {alignment_score}')
        else:
            logger.info(f'Back-translation passed - alignment score: {alignment_score}')

        confidence_adjustment=alignment_score-0.5

        return {
            "back_translated_question": back_translated_question,
            "keyword_overlap_score": round(keyword_score, 3),
            "semantic_similarity_score": round(semantic_score, 3),
            "alignment_score": round(alignment_score, 3),
            "is_hallucination": is_hallucination,
            "confidence_adjustment": round(confidence_adjustment, 3)
        }

class ResultSanityChecker:
    '''This verifies the actual data return by the query makes sense 
    and values are not out of range'''

    def __init__(self):
        '''Defines threshold for each sanity check'''
        self.null_threshold=0.5
        self.min_date=datetime(2020,1,1)
        self.max_date=datetime(2030,12,31)

    def check_empty_result(self,data:list)->Dict[str,Any]:
        '''checks if the query returns zero rows'''
        if len(data)==0:
            return {
                'passed':False,
                'check':'empty_result',
                'message':(
                    'Query returned 0 rows. This may indicate an overly'
                    'restrictive WHERE clause or incorrect JOIN condition.'
                    'Verify the query logic is correct'
                )
            }
        return {
            'passed':True,
            'check':'empty_result',
            'message':f'Result contains {len(data)} row - non empty'
        }
    
    def check_null_density(self,data:list,columns:list)-> Dict[str,Any]:
        '''Checks if columns has too many null values'''
        if not data:
            return{
                'passed':True,
                'check':'null_density',
                'message':'No data to check'
            }
        # Convert to dataframe for easy operations
        df=pd.DataFrame(data)

        #Track which column has too many null values
        null_heavy_column=[]

        for col in columns:
            if col not in df.columns:
                continue
            
            total_rows=len(df)
            null_count=df[col].isna().sum()

            # Calculate what fraction of values are null
            null_fraction=null_count/total_rows

            #Flag if its above the threshold
            if null_fraction>self.null_threshold:
                null_heavy_column.append({
                    'column':col,
                    'null_fraction':round(float(null_fraction),3),
                    'null_count':int(null_count),
                    'total_rows':total_rows

                })
        if null_heavy_column:
            return{
                'passed':False,
                'check':'null_density',
                'message': (
                    f'High Null density detected in column'
                    f'{[c['column'] for c in null_heavy_column]}'
                    f'This may indicate a bad JOIN condition'
                ),
                'null_heavy_columns':null_heavy_column
            }
        return{
            'passed':True,
            'check':'null_density',
            'message':'No columns had excessive null values'
        }

    def check_numeric_range(self,data:list,columns:list)->Dict[str,Any]:
        '''Checks if the numeric aggregated values are within the believeable range'''

        if not data:
            return {
                'passed':True,
                'check':'numeric_range',
                'message':' No data to check'
            }
        df=pd.DataFrame(data)
        suspicious_column=[]

        # Keywords that indicate the column should be non negative
        positve_keywords={
            "total", "amount", "revenue", "count",
            "quantity", "price", "sum", "avg", "average"
        }

        for col in columns:
            if col not in df.columns:
                continue
        
            # Only check numeric column
            if not pd.api.types.is_numeric_dtype(df[col]):
                continue
            col_lower=col.lower()
            
            # check if the column name suggested should be positive 
            is_positve_column=any(
                keyword in col_lower for keyword in positve_keywords
            )

            if is_positve_column:
                # Check for negative values
                has_negative=(df[col]<0).any()

                # check for large values 
                has_extreme_values = (df[col] > 1_000_000_000).any()

                if has_negative:
                    suspicious_column.append(
                        f"{col} contains negative values"
                    )
                if has_extreme_values:
                    suspicious_column.append(
                        f"{col} contains extremely large values (>1B)"
                    )
        if suspicious_column:
            return{
                'passed':False,
                'check':'numeric_range',
                'message': (
                    f'Suspicious numeric values detected:'
                    f"{';'.join(suspicious_column)}"
                )
            }
        return {
            'passed':True,
            'check':'numeric_range',
            'message':'No suspicious numeric values detected'
        }

    def check_date_ranges(self, data: list, columns: list) -> Dict[str, Any]:
        '''Checks if date values fall within the expected timespan.'''
        if not data:
            return {
                "passed": True,
                "check": "date_ranges",
                "message": "No data to check"
            }

        df = pd.DataFrame(data)
        suspicious_date_columns = []

        # Keywords that indicate a column contains dates
        date_keywords = {"date", "created", "updated", "timestamp", "time"}

        for col in columns:
            if col not in df.columns:
                continue

            col_lower = col.lower()
            
            # Only check columns with date related names
            is_date_column = any(
                keyword in col_lower for keyword in date_keywords
            )

            if not is_date_column:
                continue

            # Try to parse each value as a datetime
            out_of_range = []
            for val in df[col].dropna():
                try:
                    # Handle both string and datetime objects
                    if isinstance(val, str):
                        parsed_date = datetime.fromisoformat(val)
                    elif isinstance(val, datetime):
                        parsed_date = val
                    else:
                        # Try converting using pandas
                        parsed_date = pd.Timestamp(val).to_pydatetime()

                    # Check if date is outside our believable range
                    if parsed_date < self.min_date or parsed_date > self.max_date:
                        out_of_range.append(str(parsed_date))

                except (ValueError, TypeError):
                    # Can't parse this value skip it
                    continue

            if out_of_range:
                suspicious_date_columns.append({
                    "column": col,
                    "out_of_range_values": out_of_range[:3]
                })

        if suspicious_date_columns:
            return {
                "passed": False,
                "check": "date_ranges",
                "message": (
                    f"Date values outside expected range "
                    f"({self.min_date.year}–{self.max_date.year}) "
                    f"detected in: "
                    f"{[c['column'] for c in suspicious_date_columns]}"
                ),
                "suspicious_columns": suspicious_date_columns
            }

        return {
            "passed": True,
            "check": "date_ranges",
            "message": "Date values are within expected range"
        }

    def check(self, data:list,column:list)->Dict[str,Any]:
        # Running all checks
        logger.info(f"Running sanity checks on {len(data)} rows")
        check_results=[
            self.check_empty_result(data),
            self.check_null_density(data,column),
            self.check_date_ranges(data, column),
            self.check_numeric_range(data, column),
        ]
        
        # Collect names of failed checks
        failed_checks = [
            r["check"] for r in check_results if not r["passed"]
        ]

        # Collect warning messages from failed checks
        warnings = [
            r["message"] for r in check_results if not r["passed"]
        ]

        # Calculate sanity score — fraction of checks that passed
        sanity_score = (
            len(check_results) - len(failed_checks)
        ) / len(check_results)
        
        if failed_checks:
            logger.warning(f'Sanity checks failed:{failed_checks}')
        else:
            logger.info('All sanity checkss passed')

        return {
            "all_passed": len(failed_checks) == 0,
            "checks": check_results,
            "failed_checks": failed_checks,
            "sanity_score": round(sanity_score, 3),
            "warnings": warnings
        } 

class MultiQueryValidator:
    '''Generates two independant SQL queries for same question using different approaches
        executes both and compare the result'''
    
    def __init__(self):
        '''Initialise OpenAI client and Query Executor'''
        self.client=OpenAI()
        self.executor=QueryExecutor()

    def generate_alternative_sql(self, question:str, primary_sql:str,schema:Dict[str,Any])->str:
        '''Asks OpenAI to generate different SQL approach for the same Question
            Here we also pass the primary sql that was generated by the first LLM
            so the new sql query is different from the primary sql'''
        
        
        # Format schema table for prompt
        schema_text=''
        for table_name,table_info in schema['tables'].items():
            cols=[c['name'] for c in table_info['columns']]
            schema_text+=f'TABLE {table_name}: {', '.join(cols)}\n'

        prompt = f"""You are a SQL expert. A question has already been 
                    answered with one SQL approach. Generate a DIFFERENT SQL query that 
                    answers the same question using an alternative approach.

                    Database schema:
                    {schema_text}

                    Question: {question}

                    First SQL approach (DO NOT copy this):
                    {primary_sql}

                    Write a different PostgreSQL SELECT query that answers the same question.
                    Use a different approach — if the first uses JOIN, use a subquery.
                    If the first uses subquery, use JOIN.
                    Return ONLY the SQL query, no explanation, no markdown, no backticks."""
        response=self.client.chat.completions.create(
            model='gpt-4o-mini',
            messages=[
                {
                    'role':'system',
                    'content':(
                        'You are a SQL expert. Generate alternative SQL'
                        'query using different approch then shown'
                        'Return only SQL query.'
                    )
                },
                {
                    'role':'user',
                    'content':prompt
                }
            ],
            temperature=0.3,
            max_tokens=300
        )

        alternative_sql = response.choices[0].message.content.strip() # type: ignore
        # Removing markdown code fences if present
        if alternative_sql.startswith('```'):
            alternative_sql=alternative_sql[alternative_sql.find('\n'):]
            alternative_sql=alternative_sql.replace("```","").strip()
        
        # Validate the SQL and if invalid then retry with stricter prompt
        import sqlparse
        parsed=sqlparse.parse(alternative_sql)
        is_valid=parsed and parsed[0].tokens

        if not is_valid:
            logger.warning("Alternative SQL failed validation, retrying with stricter prompt")
            retry_prompt=f'''Write a valid Postgres SQL SELECT Query to answer:
            {question}
            schema text
            {schema_text}
            Rules:
            - Use subquery approach only
            - FROM comes before JOIN — never put JOIN after WHERE
            - Return ONLY the SQL, no explanation
            SQL:'''

            retry_response=self.client.chat.completions.create(
                model='gpt-4o-mini',
                messages=[
                    {
                        'role':'system',
                        'content':'You are a SQL expert. Only return valid Postgres SQL'
                    },
                    {
                        'role':'user',
                        'content':retry_prompt
                    }
                ],
                temperature=0,
                max_tokens=300
            )

            alternative_sql = retry_response.choices[0].message.content.strip() # type: ignore

            if alternative_sql.startswith("```"):
                alternative_sql = alternative_sql[alternative_sql.find("\n"):]
                alternative_sql = alternative_sql.replace("```", "").strip()
        logger.info(f'Alternate SQL generated: {alternative_sql[:80]}...')
        return alternative_sql

    def compare_results(self,result1:Dict[str,Any],result2:Dict[str,Any],)->Dict[str,Any]:
        '''Compares the result of two independantly executed quesries
            Parameter: 
            result1-> result dict for first query
            result2-> result dict form second query
            
            Here we are comparing Row count, Column Overlap, Value Similarity
            Agreement score:
            - 1.0 = row count AND columns AND values all match
            - 0.7 = row count AND columns match, values differ slightly
            - 0.3 = only row count matches
            - 0.0 = nothing matches or one query failed'''
        # If either query fails to execute we cant compare
        if not result1['success'] or not result2['success']:
            return {
                'agree':False,
                'agreement_score':0.0,
                'explanation':(
                    'Could not compare, one or both queries failed to execute. '
                    f'Query 1: {'success' if result1['success'] else result1['error']}',
                    f'Query 2: {'success' if result2['success'] else result2['error']}'
                )
            }
        
        score=0.0
        explanations=[]
        # Compare Row Counts
        rows1=result1['row_count']
        rows2=result2['row_count']

        if rows1==rows2:
            score+=0.4
            explanations.append(f'Row counts match ({rows1} rows)')
        else:
            explanations.append(
                f'Row count mismatched: query 1 returned {rows1}'
                f'query 2 returned {rows2}'
            )
        # Compare Column Overlap

        cols1=result1['columns']
        cols2=result2['columns']
        common_cols = set(cols1) & set(cols2)

        if len(common_cols) > 0:
            overlap_ratio=len(common_cols)/max(len(cols1),len(cols2))
            score+= 0.3 * overlap_ratio
            explanations.append(
                f'column overlap: {len(common_cols)} shared columns'
                f'({overlap_ratio:.0%} overlap)'
            )
        else:
            explanations.append('No common columns betweeen results')
        
        # Checks 3 Numeric value similarity 
        if result1['data'] and result2['data']:
            df1=pd.DataFrame(result1['data'])
            df2=pd.DataFrame(result2['data'])

            # Finding numeric value in both ther dataframe
            # Convert Decimal columns to float first
            for col in df1.columns:
                if df1[col].apply(lambda x: isinstance(x, decimal.Decimal)).any():
                    df1[col] = df1[col].astype(float)

            for col in df2.columns:
                if df2[col].apply(lambda x: isinstance(x, decimal.Decimal)).any():
                    df2[col] = df2[col].astype(float)
                
            numeric_cols1=df1.select_dtypes(include=['number']).columns
            numeric_cols2=df2.select_dtypes(include=['number']).columns

            #Find common numerical columns 
            common_numeric= set(numeric_cols1) & set(numeric_cols2)

            if common_numeric:
                # Take the first common numeric column
                check_col=list(common_numeric)[0]
                sum1=float(df1[check_col].sum())
                sum2=float(df2[check_col].sum())

                #Calculate how similar the sums are
                if sum1==0 and sum2==0:
                    score+=0.3
                    explanations.append(
                        f'Numeric value matched (both zero for {check_col})'
                    )

                elif max(abs(sum1), abs(sum2)) > 0:
                    diff_ratio=abs(sum1-sum2)/max(abs(sum1),abs(sum2))
                
                    if diff_ratio<0.01:
                        # less than 1% difference is ideally identical
                        score += 0.3
                        explanations.append(
                            f"Numeric values match closely for {check_col} "
                            f"(sum1={sum1:.2f}, sum2={sum2:.2f})"
                        )
                    elif diff_ratio < 0.1:
                        # Less than 10% difference — close enough
                        score += 0.15
                        explanations.append(
                            f"Numeric values slightly differ for {check_col} "
                            f"(sum1={sum1:.2f}, sum2={sum2:.2f}, "
                            f"diff={diff_ratio:.1%})"
                        )
                    else:
                        # More than 10% difference — significant divergence
                        explanations.append(
                            f"Numeric values diverge significantly for "
                            f"{check_col} "
                            f"(sum1={sum1:.2f}, sum2={sum2:.2f}, "
                            f"diff={diff_ratio:.1%})"
                        )
            else:
                explanations.append('No common numeric values to append ')
        
        # Determine overall agreement
        agree = score >= 0.7

        return {
            "agree": agree,
            "agreement_score": round(score, 3),
            "explanation": " | ".join(explanations)
        }

    def validate(self,question:str, primary_sql:str,schema:Dict[str,Any])->Dict[str,Any]:
        
        # 1. Executes teh priamry query
        logger.info("Executing primary SQL")
        primary_result=self.executor.execute(primary_sql)
        
        # 2. Generate alternative SQL
        logger.info("Generating alternative SQL approach")
        alternative_sql=self.generate_alternative_sql(question,primary_sql,schema)
        
        # 3. Execute alternative SQL
        logger.info(f"Alternative SQL generated: {alternative_sql[:80]}...")
        alternative_result=self.executor.execute(alternative_sql)
        # If the alternative solution fails retry the generation once
        if not alternative_result['success']:
            logger.warning(
            f"Alternative SQL execution failed: {alternative_result['error']}. "
            f"Retrying generation..."
        )

        alternative_sql=self.generate_alternative_sql(question,primary_sql,schema)
        alternative_result=self.executor.execute(alternative_sql)

        
        # 4. Compare the result
        comparison=self.compare_results(primary_result,alternative_result)
        
        # 5. Calculate confidence adjustment
        if comparison['agreement_score']>=0.7:
            confidence_adjustment=0.2
        elif comparison['agreement_score']>=0.4:
            confidence_adjustment=0.0
        else:
            confidence_adjustment=-0.3
        
        return {
            "agree": comparison["agree"],
            "agreement_score": comparison["agreement_score"],
            "primary_sql": primary_sql,
            "alternative_sql": alternative_sql,
            "primary_result": primary_result,
            "alternative_result": alternative_result,
            "explanation": comparison["explanation"],
            "confidence_adjustment": confidence_adjustment
        }

class ConfidenceScorer:
    '''Combines all the halucination detection signals into one final confidence score bwetween 0.0 and 1.0
    Weights:
        Back-translation-----> 35% (highest directly checks SQL meaning)
        LLM confidence-------> 30% (useful but LLMs can be confidently wrong)
        Sanity score --------> 20% (secondary checks result quality)
        Multi-query ---------> 15% (bonus signal confirms with second approach) '''

    # Confidence Threshold for user facing labels 
    HIGH_CONFIDENCE=0.8
    MEDIUM_CONFIDENCE=0.5

    # Weights for each signal - must sum to 1.0
    WEIGHTS={
        'llm_confidence':0.30,
        'back_translation':0.35,
        'sanity_score':0.20,
        'multi_query':0.15
    }

    def __init__(self):
        self.logger=get_logger(__name__)
    
    def get_confidence_label(self, score:float)->str:
        '''Converst the numeric score to human readable label'''
        if score>=self.HIGH_CONFIDENCE:
            return 'HIGH'
        elif score>=self.MEDIUM_CONFIDENCE:
            return 'MEDIUM'
        else:
            return 'LOW'
    def get_recommendation(self,score:float,failed_checks:List)->str:
        '''Generates a human readable recommendation based on the score and which specific checks failed'''
        if score>=self.HIGH_CONFIDENCE:
            return 'Result looks reliable. Proceed with confidence'
        recommendations=[]

        # Give specific advices based on which checks failed
        if 'back_translation' in failed_checks:
            recommendations.append(
                'The SQL may not answer your exact question - '
                'review the generated query carefully'
            )
        if 'sanity_check' in failed_checks:
            recommendations.append(
                'Result contains unusual value - ' 
                'Check for null heavy columns or unexpected ranges'
            )
        if 'multi_query' in failed_checks:
            recommendations.append(
                'Two SQL approaches gave different results'
                'the answer maybe ambiguous or the query complex'
            )
        if not recommendations:
            recommendations.append(
                'Results are plausible but verify before making decisions'
            )
        return ' | '. join(recommendations)
    
    def compute(self,llm_confidence:float,back_translation_result:Dict[str,Any],sanity_result:Dict[str,Any],multi_query_result:Dict[str,Any])->Dict[str,Any]:
        """Compute final aggregated confidence score (0.0-1.0)"""
        self.logger.info('computing the final confidence score')
        
        # Extract Individual signal score
        signal_llm=max(0.0,min(1.0,llm_confidence))

        # Back translation alignment score
        signal_back_translation=back_translation_result.get('alignment_score',0.5)

        # Sanity Score
        signal_sanity=sanity_result.get('sanity_score',1.0)

        # Multi Query Score
        signal_multi_query=multi_query_result.get('agreement_score',0.5)

        # Weights and Sum
        weighted_score=(
            self.WEIGHTS['llm_confidence'] * signal_llm +
            self.WEIGHTS['back_translation'] * signal_back_translation +
            self.WEIGHTS['sanity_score'] * signal_sanity +
            self.WEIGHTS['multi_query'] * signal_multi_query
        )

        # Final Score normalised between 0.0 - 1.0
        final_score=round(max(0.0, min(1.0,weighted_score)),3)

        # Identifying which checks failed
        failed_checks=[]
        
        if back_translation_result.get('is_hallucination', False):
            failed_checks.append('back_translation')
        
        if not sanity_result.get('all_passed',True):
            failed_checks.append('sanity')
        
        if not multi_query_result.get('agree',True):
            failed_checks.append('multi_query')
        
        confidence_label=self.get_confidence_label(final_score)
        recommendation=self.get_recommendation(final_score,failed_checks)

        signal_breakdown={
            'llm_confidence':{
                'raw_score':round(signal_llm,3),
                'weight':self.WEIGHTS['llm_confidence'],
                'contribution':round(
                    self.WEIGHTS['llm_confidence'] * signal_llm,3
                )
            },
            "back_translation": {
                "raw_score": round(signal_back_translation, 3),
                "weight": self.WEIGHTS["back_translation"],
                "contribution": round(
                    self.WEIGHTS["back_translation"] * signal_back_translation,
                    3
                ),
                "is_hallucination": back_translation_result.get(
                    "is_hallucination", False
                )
            },
            "sanity_check": {
                "raw_score": round(signal_sanity, 3),
                "weight": self.WEIGHTS["sanity_score"],
                "contribution": round(
                    self.WEIGHTS["sanity_score"] * signal_sanity, 3
                ),
                "failed_checks": sanity_result.get("failed_checks", [])
            },
            "multi_query": {
                "raw_score": round(signal_multi_query, 3),
                "weight": self.WEIGHTS["multi_query"],
                "contribution": round(
                    self.WEIGHTS["multi_query"] * signal_multi_query, 3
                ),
                "agree": multi_query_result.get("agree", True)
            }
                
        }

        # Log the result
        self.logger.info(
            f'Confidence score computed:{final_score}({confidence_label})'
        )
        if failed_checks:
            self.logger.warning(f'Failed check: {failed_checks}')
        
        return {
            'final_score':final_score,
            'confidence_label':confidence_label,
            'recommendation':recommendation,
            'signal_breakdown':signal_breakdown,
            'failed_checks':failed_checks
        }


        


        


        

    


        







            
        




        


if __name__ == "__main__":
    verifier = BackTranslationVerifier()

# Test case 1
    print("TEST 1: Good SQL")
    print("-" * 50)
    original = "Which customers have spent the most money?"
    sql = """SELECT c.name, SUM(o.total_amount) AS total_spent
                FROM customers c
                JOIN orders o ON c.customer_id = o.customer_id
                GROUP BY c.customer_id, c.name
                ORDER BY total_spent DESC LIMIT 100"""

    result = verifier.verify(original, sql)
    print(f"Original question:      {original}")
    print(f"Back-translated:        {result['back_translated_question']}")
    print(f"Keyword overlap:        {result['keyword_overlap_score']}")
    print(f"Semantic similarity:    {result['semantic_similarity_score']}")
    print(f"Alignment score:        {result['alignment_score']}")
    print(f"Is hallucination:       {result['is_hallucination']}")
    print(f"Confidence adjustment:  {result['confidence_adjustment']}")
# Test case 2
    print("\nTEST 2: Wrong SQL")
    print("-" * 50)
    original2 = "Which customers have spent the most money?"
    wrong_sql = """SELECT c.name, COUNT(o.order_id) AS order_count
                    FROM customers c
                    JOIN orders o ON c.customer_id = o.customer_id
                    GROUP BY c.customer_id, c.name
                    ORDER BY order_count DESC LIMIT 100"""

    result2 = verifier.verify(original2, wrong_sql)
    print(f"Original question:      {original2}")
    print(f"Back-translated:        {result2['back_translated_question']}")
    print(f"Keyword overlap:        {result2['keyword_overlap_score']}")
    print(f"Semantic similarity:    {result2['semantic_similarity_score']}")
    print(f"Alignment score:        {result2['alignment_score']}")
    print(f"Is hallucination:       {result2['is_hallucination']}")
    print(f"Confidence adjustment:  {result2['confidence_adjustment']}")


    # -------------------------------------------------------
    # Sanity Checker Tests
    # -------------------------------------------------------
    print("\n" + "=" * 60)
    print("TESTING RESULT SANITY CHECKER")
    print("=" * 60)

    checker = ResultSanityChecker()

    # Test 1: Normal good results
    print("\nTest 1: Normal results")
    print("-" * 50)
    good_data = [
        {"customer_name": "Alice", "total_spent": 1379.97},
        {"customer_name": "Bob", "total_spent": 1349.97},
        {"customer_name": "Carol", "total_spent": 679.98}
    ]
    result = checker.check(good_data, ["customer_name", "total_spent"])
    print(f"All passed: {result['all_passed']}")
    print(f"Sanity score: {result['sanity_score']}")
    print(f"Warnings: {result['warnings']}")

    # Test 2: Empty results
    print("\nTest 2: Empty results")
    print("-" * 50)
    result2 = checker.check([], ["customer_name", "total_spent"])
    print(f"All passed: {result2['all_passed']}")
    print(f"Failed checks: {result2['failed_checks']}")
    print(f"Warnings: {result2['warnings']}")

    # Test 3: NULL heavy results (bad JOIN simulation)
    print("\nTest 3: NULL heavy results")
    print("-" * 50)
    null_data = [
        {"customer_name": "Alice", "total_spent": None},
        {"customer_name": "Bob", "total_spent": None},
        {"customer_name": "Carol", "total_spent": None},
        {"customer_name": "David", "total_spent": 100.0},
    ]
    result3 = checker.check(null_data, ["customer_name", "total_spent"])
    print(f"All passed: {result3['all_passed']}")
    print(f"Failed checks: {result3['failed_checks']}")
    print(f"Warnings: {result3['warnings']}")

    # Test 4: Negative values
    print("\nTest 4: Negative revenue")
    print("-" * 50)
    negative_data = [
        {"category": "Electronics", "total_revenue": -500.00},
        {"category": "Books", "total_revenue": 200.00}
    ]
    result4 = checker.check(negative_data, ["category", "total_revenue"])
    print(f"All passed: {result4['all_passed']}")
    print(f"Failed checks: {result4['failed_checks']}")
    print(f"Warnings: {result4['warnings']}")


    # -------------------------------------------------------
    # Multi Query Validator
    # -------------------------------------------------------
    print("\n" + "=" * 60)
    print("TESTING MULTI-QUERY VALIDATOR")
    print("=" * 60)

    # pyrefly: ignore [missing-import]
    from schema_extractor import SchemaExtractor 
    extractor = SchemaExtractor()
    schema = extractor.extract_full_schema()

    validator = MultiQueryValidator()

    # Test: Two approaches for the same question
    print("\nTest: Which customers spent the most money?")
    print("-" * 50)

    primary_sql = """SELECT c.name, SUM(o.total_amount) AS total_spent
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.name
    ORDER BY total_spent DESC LIMIT 100"""

    result = validator.validate(
        "Which customers spent the most money?",
        primary_sql,
        schema
    )

    print(f"Agree: {result['agree']}")
    print(f"Agreement score: {result['agreement_score']}")
    print(f"Explanation: {result['explanation']}")
    print(f"Confidence adjustment: {result['confidence_adjustment']}")
    print(f"\nAlternative SQL generated:\n{result['alternative_sql']}")
    print(f"\nPrimary result rows: {result['primary_result']['row_count']}")
    print(f"Alternative result rows: {result['alternative_result']['row_count']}")


    # -------------------------------------------------------
        # Confidence score
    # -------------------------------------------------------

    print("\n" + "=" * 60)
    print("TESTING CONFIDENCE SCORER")
    print("=" * 60)

    scorer = ConfidenceScorer()

    # Test 1: All signals strong — should be HIGH confidence
    print("\nTest 1: All signals strong (should be HIGH)")
    print("-" * 50)
    result = scorer.compute(
        llm_confidence=0.95,
        back_translation_result={
            "alignment_score": 0.85,
            "is_hallucination": False
        },
        sanity_result={
            "all_passed": True,
            "sanity_score": 1.0,
            "failed_checks": []
        },
        multi_query_result={
            "agree": True,
            "agreement_score": 1.0
        }
    )
    print(f"Final score:      {result['final_score']}")
    print(f"Label:            {result['confidence_label']}")
    print(f"Recommendation:   {result['recommendation']}")
    print(f"Signal breakdown:")
    for signal, details in result['signal_breakdown'].items():
        print(f"  {signal}: {details['raw_score']} × {details['weight']} = {details['contribution']}")

    # Test 2: Back-translation failed — should be LOW confidence
    print("\nTest 2: Back-translation failed (should be LOW)")
    print("-" * 50)
    result2 = scorer.compute(
    llm_confidence=0.50,          
    back_translation_result={
        "alignment_score": 0.2,
        "is_hallucination": True
    },
    sanity_result={
        "all_passed": False,       
        "sanity_score": 0.5,      
        "failed_checks": ["null_density"]
    },
    multi_query_result={
        "agree": False,
        "agreement_score": 0.3
    }
)
    print(f"Final score:      {result2['final_score']}")
    print(f"Label:            {result2['confidence_label']}")
    print(f"Recommendation:   {result2['recommendation']}")
    print(f"Failed checks:    {result2['failed_checks']}")

    # Test 3: Mixed signals — should be MEDIUM confidence
    print("\nTest 3: Mixed signals (should be MEDIUM)")
    print("-" * 50)
    result3 = scorer.compute(
        llm_confidence=0.75,
        back_translation_result={
            "alignment_score": 0.6,
            "is_hallucination": False
        },
        sanity_result={
            "all_passed": False,
            "sanity_score": 0.75,
            "failed_checks": ["null_density"]
        },
        multi_query_result={
            "agree": True,
            "agreement_score": 0.7
        }
    )
    print(f"Final score:      {result3['final_score']}")
    print(f"Label:            {result3['confidence_label']}")
    print(f"Recommendation:   {result3['recommendation']}")
    print(f"Failed checks:    {result3['failed_checks']}")


        
            
            
            

        
        





        